// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBuffers/GarageStatus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GarageStatus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* GarageStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GarageStatus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProtocolBuffers_2fGarageStatus_2eproto() {
  protobuf_AddDesc_ProtocolBuffers_2fGarageStatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProtocolBuffers/GarageStatus.proto");
  GOOGLE_CHECK(file != NULL);
  GarageStatus_descriptor_ = file->message_type(0);
  static const int GarageStatus_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, garageid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, isclosed_),
  };
  GarageStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GarageStatus_descriptor_,
      GarageStatus::default_instance_,
      GarageStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GarageStatus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProtocolBuffers_2fGarageStatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GarageStatus_descriptor_, &GarageStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ProtocolBuffers_2fGarageStatus_2eproto() {
  delete GarageStatus::default_instance_;
  delete GarageStatus_reflection_;
}

void protobuf_AddDesc_ProtocolBuffers_2fGarageStatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"ProtocolBuffers/GarageStatus.proto\"E\n\014"
    "GarageStatus\022\020\n\010garageId\030\001 \002(\r\022\021\n\ttimest"
    "amp\030\002 \002(\004\022\020\n\010isClosed\030\003 \002(\010", 107);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProtocolBuffers/GarageStatus.proto", &protobuf_RegisterTypes);
  GarageStatus::default_instance_ = new GarageStatus();
  GarageStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProtocolBuffers_2fGarageStatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProtocolBuffers_2fGarageStatus_2eproto {
  StaticDescriptorInitializer_ProtocolBuffers_2fGarageStatus_2eproto() {
    protobuf_AddDesc_ProtocolBuffers_2fGarageStatus_2eproto();
  }
} static_descriptor_initializer_ProtocolBuffers_2fGarageStatus_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GarageStatus::kGarageIdFieldNumber;
const int GarageStatus::kTimestampFieldNumber;
const int GarageStatus::kIsClosedFieldNumber;
#endif  // !_MSC_VER

GarageStatus::GarageStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GarageStatus::InitAsDefaultInstance() {
}

GarageStatus::GarageStatus(const GarageStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GarageStatus::SharedCtor() {
  _cached_size_ = 0;
  garageid_ = 0u;
  timestamp_ = GOOGLE_ULONGLONG(0);
  isclosed_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GarageStatus::~GarageStatus() {
  SharedDtor();
}

void GarageStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GarageStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GarageStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GarageStatus_descriptor_;
}

const GarageStatus& GarageStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ProtocolBuffers_2fGarageStatus_2eproto();
  return *default_instance_;
}

GarageStatus* GarageStatus::default_instance_ = NULL;

GarageStatus* GarageStatus::New() const {
  return new GarageStatus;
}

void GarageStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    garageid_ = 0u;
    timestamp_ = GOOGLE_ULONGLONG(0);
    isclosed_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GarageStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 garageId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &garageid_)));
          set_has_garageid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // required uint64 timestamp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_isClosed;
        break;
      }

      // required bool isClosed = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isClosed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isclosed_)));
          set_has_isclosed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GarageStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 garageId = 1;
  if (has_garageid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->garageid(), output);
  }

  // required uint64 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->timestamp(), output);
  }

  // required bool isClosed = 3;
  if (has_isclosed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isclosed(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GarageStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 garageId = 1;
  if (has_garageid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->garageid(), target);
  }

  // required uint64 timestamp = 2;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->timestamp(), target);
  }

  // required bool isClosed = 3;
  if (has_isclosed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isclosed(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GarageStatus::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 garageId = 1;
    if (has_garageid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->garageid());
    }

    // required uint64 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->timestamp());
    }

    // required bool isClosed = 3;
    if (has_isclosed()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GarageStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GarageStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GarageStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GarageStatus::MergeFrom(const GarageStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_garageid()) {
      set_garageid(from.garageid());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_isclosed()) {
      set_isclosed(from.isclosed());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GarageStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GarageStatus::CopyFrom(const GarageStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GarageStatus::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void GarageStatus::Swap(GarageStatus* other) {
  if (other != this) {
    std::swap(garageid_, other->garageid_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(isclosed_, other->isclosed_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GarageStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GarageStatus_descriptor_;
  metadata.reflection = GarageStatus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
