// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBuffers/GarageMetaData.proto

#ifndef PROTOBUF_ProtocolBuffers_2fGarageMetaData_2eproto__INCLUDED
#define PROTOBUF_ProtocolBuffers_2fGarageMetaData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
void protobuf_AssignDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
void protobuf_ShutdownFile_ProtocolBuffers_2fGarageMetaData_2eproto();

class GarageMetaData;

// ===================================================================

class GarageMetaData : public ::google::protobuf::Message {
 public:
  GarageMetaData();
  virtual ~GarageMetaData();

  GarageMetaData(const GarageMetaData& from);

  inline GarageMetaData& operator=(const GarageMetaData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GarageMetaData& default_instance();

  void Swap(GarageMetaData* other);

  // implements Message ----------------------------------------------

  GarageMetaData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GarageMetaData& from);
  void MergeFrom(const GarageMetaData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 doorCount = 1;
  inline bool has_doorcount() const;
  inline void clear_doorcount();
  static const int kDoorCountFieldNumber = 1;
  inline ::google::protobuf::int32 doorcount() const;
  inline void set_doorcount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GarageMetaData)
 private:
  inline void set_has_doorcount();
  inline void clear_has_doorcount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 doorcount_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
  friend void protobuf_AssignDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
  friend void protobuf_ShutdownFile_ProtocolBuffers_2fGarageMetaData_2eproto();

  void InitAsDefaultInstance();
  static GarageMetaData* default_instance_;
};
// ===================================================================


// ===================================================================

// GarageMetaData

// optional int32 doorCount = 1;
inline bool GarageMetaData::has_doorcount() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GarageMetaData::set_has_doorcount() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GarageMetaData::clear_has_doorcount() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GarageMetaData::clear_doorcount() {
  doorcount_ = 0;
  clear_has_doorcount();
}
inline ::google::protobuf::int32 GarageMetaData::doorcount() const {
  return doorcount_;
}
inline void GarageMetaData::set_doorcount(::google::protobuf::int32 value) {
  set_has_doorcount();
  doorcount_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtocolBuffers_2fGarageMetaData_2eproto__INCLUDED
