// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GarageStatus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GarageStatus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* GarageStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GarageStatus_reflection_ = NULL;
const ::google::protobuf::Descriptor* GarageStatus_DoorStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GarageStatus_DoorStatus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_GarageStatus_2eproto() {
  protobuf_AddDesc_GarageStatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GarageStatus.proto");
  GOOGLE_CHECK(file != NULL);
  GarageStatus_descriptor_ = file->message_type(0);
  static const int GarageStatus_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, doors_),
  };
  GarageStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GarageStatus_descriptor_,
      GarageStatus::default_instance_,
      GarageStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GarageStatus));
  GarageStatus_DoorStatus_descriptor_ = GarageStatus_descriptor_->nested_type(0);
  static const int GarageStatus_DoorStatus_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, uniqueid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, garageid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, isclosed_),
  };
  GarageStatus_DoorStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GarageStatus_DoorStatus_descriptor_,
      GarageStatus_DoorStatus::default_instance_,
      GarageStatus_DoorStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageStatus_DoorStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GarageStatus_DoorStatus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GarageStatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GarageStatus_descriptor_, &GarageStatus::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GarageStatus_DoorStatus_descriptor_, &GarageStatus_DoorStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GarageStatus_2eproto() {
  delete GarageStatus::default_instance_;
  delete GarageStatus_reflection_;
  delete GarageStatus_DoorStatus::default_instance_;
  delete GarageStatus_DoorStatus_reflection_;
}

void protobuf_AddDesc_GarageStatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022GarageStatus.proto\"\216\001\n\014GarageStatus\022\'\n"
    "\005doors\030\001 \003(\0132\030.GarageStatus.DoorStatus\032U"
    "\n\nDoorStatus\022\020\n\010uniqueId\030\004 \002(\r\022\020\n\010garage"
    "Id\030\001 \002(\r\022\021\n\ttimestamp\030\002 \002(\r\022\020\n\010isClosed\030"
    "\003 \002(\010", 165);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GarageStatus.proto", &protobuf_RegisterTypes);
  GarageStatus::default_instance_ = new GarageStatus();
  GarageStatus_DoorStatus::default_instance_ = new GarageStatus_DoorStatus();
  GarageStatus::default_instance_->InitAsDefaultInstance();
  GarageStatus_DoorStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GarageStatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GarageStatus_2eproto {
  StaticDescriptorInitializer_GarageStatus_2eproto() {
    protobuf_AddDesc_GarageStatus_2eproto();
  }
} static_descriptor_initializer_GarageStatus_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GarageStatus_DoorStatus::kUniqueIdFieldNumber;
const int GarageStatus_DoorStatus::kGarageIdFieldNumber;
const int GarageStatus_DoorStatus::kTimestampFieldNumber;
const int GarageStatus_DoorStatus::kIsClosedFieldNumber;
#endif  // !_MSC_VER

GarageStatus_DoorStatus::GarageStatus_DoorStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GarageStatus_DoorStatus::InitAsDefaultInstance() {
}

GarageStatus_DoorStatus::GarageStatus_DoorStatus(const GarageStatus_DoorStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GarageStatus_DoorStatus::SharedCtor() {
  _cached_size_ = 0;
  uniqueid_ = 0u;
  garageid_ = 0u;
  timestamp_ = 0u;
  isclosed_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GarageStatus_DoorStatus::~GarageStatus_DoorStatus() {
  SharedDtor();
}

void GarageStatus_DoorStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GarageStatus_DoorStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GarageStatus_DoorStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GarageStatus_DoorStatus_descriptor_;
}

const GarageStatus_DoorStatus& GarageStatus_DoorStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GarageStatus_2eproto();
  return *default_instance_;
}

GarageStatus_DoorStatus* GarageStatus_DoorStatus::default_instance_ = NULL;

GarageStatus_DoorStatus* GarageStatus_DoorStatus::New() const {
  return new GarageStatus_DoorStatus;
}

void GarageStatus_DoorStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    uniqueid_ = 0u;
    garageid_ = 0u;
    timestamp_ = 0u;
    isclosed_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GarageStatus_DoorStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 garageId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &garageid_)));
          set_has_garageid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // required uint32 timestamp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_isClosed;
        break;
      }

      // required bool isClosed = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isClosed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isclosed_)));
          set_has_isclosed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_uniqueId;
        break;
      }

      // required uint32 uniqueId = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_uniqueId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uniqueid_)));
          set_has_uniqueid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GarageStatus_DoorStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 garageId = 1;
  if (has_garageid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->garageid(), output);
  }

  // required uint32 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->timestamp(), output);
  }

  // required bool isClosed = 3;
  if (has_isclosed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isclosed(), output);
  }

  // required uint32 uniqueId = 4;
  if (has_uniqueid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->uniqueid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GarageStatus_DoorStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 garageId = 1;
  if (has_garageid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->garageid(), target);
  }

  // required uint32 timestamp = 2;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->timestamp(), target);
  }

  // required bool isClosed = 3;
  if (has_isclosed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isclosed(), target);
  }

  // required uint32 uniqueId = 4;
  if (has_uniqueid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->uniqueid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GarageStatus_DoorStatus::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 uniqueId = 4;
    if (has_uniqueid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uniqueid());
    }

    // required uint32 garageId = 1;
    if (has_garageid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->garageid());
    }

    // required uint32 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->timestamp());
    }

    // required bool isClosed = 3;
    if (has_isclosed()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GarageStatus_DoorStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GarageStatus_DoorStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GarageStatus_DoorStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GarageStatus_DoorStatus::MergeFrom(const GarageStatus_DoorStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uniqueid()) {
      set_uniqueid(from.uniqueid());
    }
    if (from.has_garageid()) {
      set_garageid(from.garageid());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_isclosed()) {
      set_isclosed(from.isclosed());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GarageStatus_DoorStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GarageStatus_DoorStatus::CopyFrom(const GarageStatus_DoorStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GarageStatus_DoorStatus::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void GarageStatus_DoorStatus::Swap(GarageStatus_DoorStatus* other) {
  if (other != this) {
    std::swap(uniqueid_, other->uniqueid_);
    std::swap(garageid_, other->garageid_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(isclosed_, other->isclosed_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GarageStatus_DoorStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GarageStatus_DoorStatus_descriptor_;
  metadata.reflection = GarageStatus_DoorStatus_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int GarageStatus::kDoorsFieldNumber;
#endif  // !_MSC_VER

GarageStatus::GarageStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GarageStatus::InitAsDefaultInstance() {
}

GarageStatus::GarageStatus(const GarageStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GarageStatus::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GarageStatus::~GarageStatus() {
  SharedDtor();
}

void GarageStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GarageStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GarageStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GarageStatus_descriptor_;
}

const GarageStatus& GarageStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GarageStatus_2eproto();
  return *default_instance_;
}

GarageStatus* GarageStatus::default_instance_ = NULL;

GarageStatus* GarageStatus::New() const {
  return new GarageStatus;
}

void GarageStatus::Clear() {
  doors_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GarageStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .GarageStatus.DoorStatus doors = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_doors:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_doors()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_doors;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GarageStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .GarageStatus.DoorStatus doors = 1;
  for (int i = 0; i < this->doors_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->doors(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GarageStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .GarageStatus.DoorStatus doors = 1;
  for (int i = 0; i < this->doors_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->doors(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GarageStatus::ByteSize() const {
  int total_size = 0;

  // repeated .GarageStatus.DoorStatus doors = 1;
  total_size += 1 * this->doors_size();
  for (int i = 0; i < this->doors_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->doors(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GarageStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GarageStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GarageStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GarageStatus::MergeFrom(const GarageStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  doors_.MergeFrom(from.doors_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GarageStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GarageStatus::CopyFrom(const GarageStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GarageStatus::IsInitialized() const {

  for (int i = 0; i < doors_size(); i++) {
    if (!this->doors(i).IsInitialized()) return false;
  }
  return true;
}

void GarageStatus::Swap(GarageStatus* other) {
  if (other != this) {
    doors_.Swap(&other->doors_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GarageStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GarageStatus_descriptor_;
  metadata.reflection = GarageStatus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
