// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBuffers/GarageMetaData.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GarageMetaData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* GarageMetaData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GarageMetaData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProtocolBuffers_2fGarageMetaData_2eproto() {
  protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProtocolBuffers/GarageMetaData.proto");
  GOOGLE_CHECK(file != NULL);
  GarageMetaData_descriptor_ = file->message_type(0);
  static const int GarageMetaData_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageMetaData, doorcount_),
  };
  GarageMetaData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GarageMetaData_descriptor_,
      GarageMetaData::default_instance_,
      GarageMetaData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageMetaData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GarageMetaData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GarageMetaData));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProtocolBuffers_2fGarageMetaData_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GarageMetaData_descriptor_, &GarageMetaData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ProtocolBuffers_2fGarageMetaData_2eproto() {
  delete GarageMetaData::default_instance_;
  delete GarageMetaData_reflection_;
}

void protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n$ProtocolBuffers/GarageMetaData.proto\"#"
    "\n\016GarageMetaData\022\021\n\tdoorCount\030\001 \001(\005", 75);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProtocolBuffers/GarageMetaData.proto", &protobuf_RegisterTypes);
  GarageMetaData::default_instance_ = new GarageMetaData();
  GarageMetaData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProtocolBuffers_2fGarageMetaData_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProtocolBuffers_2fGarageMetaData_2eproto {
  StaticDescriptorInitializer_ProtocolBuffers_2fGarageMetaData_2eproto() {
    protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
  }
} static_descriptor_initializer_ProtocolBuffers_2fGarageMetaData_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GarageMetaData::kDoorCountFieldNumber;
#endif  // !_MSC_VER

GarageMetaData::GarageMetaData()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GarageMetaData::InitAsDefaultInstance() {
}

GarageMetaData::GarageMetaData(const GarageMetaData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GarageMetaData::SharedCtor() {
  _cached_size_ = 0;
  doorcount_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GarageMetaData::~GarageMetaData() {
  SharedDtor();
}

void GarageMetaData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GarageMetaData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GarageMetaData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GarageMetaData_descriptor_;
}

const GarageMetaData& GarageMetaData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ProtocolBuffers_2fGarageMetaData_2eproto();
  return *default_instance_;
}

GarageMetaData* GarageMetaData::default_instance_ = NULL;

GarageMetaData* GarageMetaData::New() const {
  return new GarageMetaData;
}

void GarageMetaData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    doorcount_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GarageMetaData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 doorCount = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &doorcount_)));
          set_has_doorcount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GarageMetaData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 doorCount = 1;
  if (has_doorcount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->doorcount(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GarageMetaData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 doorCount = 1;
  if (has_doorcount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->doorcount(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GarageMetaData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 doorCount = 1;
    if (has_doorcount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->doorcount());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GarageMetaData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GarageMetaData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GarageMetaData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GarageMetaData::MergeFrom(const GarageMetaData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_doorcount()) {
      set_doorcount(from.doorcount());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GarageMetaData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GarageMetaData::CopyFrom(const GarageMetaData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GarageMetaData::IsInitialized() const {

  return true;
}

void GarageMetaData::Swap(GarageMetaData* other) {
  if (other != this) {
    std::swap(doorcount_, other->doorcount_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GarageMetaData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GarageMetaData_descriptor_;
  metadata.reflection = GarageMetaData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
